version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: envyguard-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=envyguard2026**

  agent:
    build: .
    container_name: envyguard-backend
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - ConnectionStrings__RabbitMQ=amqp://admin:envyguard2026**@rabbitmq:5672